### ISSUE TITLE
Some types of errors are not been caught

### ISSUE THREAD

**Issue by zvictor** [jkyberneees/http-lambda-proxy#3]
Given a lambda fn like this:

```js
exports.handler = (event, context) => {
  throw new Error('hello world!')
}
```

`http-lambda-proxy` fails to detect this as an error. I added `console.log({ err, response })` between the lines 35 and 36 and the output I pasted below: https://github.com/jkyberneees/http-lambda-proxy/blob/429b12592df115664ae959506c44f9587af0245d/index.js#L35-L36

```js
{
  err: null,
  response: {
    StatusCode: 200,
    FunctionError: 'Unhandled',
    ExecutedVersion: '$LATEST',
    Payload: '{"errorType":"Error","errorMessage":"hello world!"}'
  }
}
```

---

Because `err: null`, the rest of the logic is executed as if the fn had executed properly. Eventually it will fail while trying to copy the non existing headers that are expected to be there.

```haskell
Error [TypeError]: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at copyHeaders (/home/node_modules/http-lambda-proxy/index.js:59:30)
    at Response.<anonymous> (/home/node_modules/http-lambda-proxy/index.js:45:9)
    at Request.<anonymous> (/home/node_modules/aws-sdk/lib/request.js:369:18)
    at Request.callListeners (/home/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/node_modules/aws-sdk/lib/state_machine.js:26:10 {
  code: 'TypeError',
  time: 2020-11-07T11:14:25.683Z
}
```

**Comment by zvictor** [comment]
btw, it might be a good to spread some [debug](http://npmjs.com/package/debug) calls around the code to help debugging cases like that 😊

**Comment by jkyberneees** [comment]
Hi @zvictor, thanks for reporting. Can I kindly ask you to review: https://github.com/jkyberneees/http-lambda-proxy/pull/5
Many Thanks

**Comment by zvictor** [comment]
Sorry for not replying on good time. I just checked the good and it looked very good.
I like the idea of specifying the expected format in the README and I also like the tests added.
I will play with the new version this week and report bugs if I find them.

Regarding the recommendation of serverless-http I am not sure about. It's a solution a don't personally like and I am happy using middy. As long as the expected output is well defined, there is no need to go for specific providers.
